input {

  file {
    path => "/logs/ahrenix.log"
    start_position => "beginning"
    codec => "json"
  }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ahrenix-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}