server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ahrenix
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.com.yp.ahrenix=DEBUG

# JWT
jwt.secret=ThisIsASecureSecretKeyForAHrenixJwtTokenGeneration123456
jwt.expiration=900000

jwt.refresh-expiration=86400000