{
 "title": "AHrenix Enterprise Dashboard",
 "tags": [
  "ahrenix",
  "springboot",
  "fintech"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Kafka Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag"
    }
   ]
  },
  {
   "title": "DB Connection Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum"
    }
   ]
  },
  {
   "title": "Authentication Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(spring_security_authentication_failures_total[1m])"
    }
   ]
  },
  {
   "title": "Redis Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "redis_connections_received_total"
    }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m])"
    }
   ]
  }
 ]
}