apiVersion: apps/v1
kind: Deployment

metadata:
  name: ahrenix-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ahrenix-backend

  template:
    metadata:
      labels:
        app: ahrenix-backend

    spec:
      containers:
        - name: ahrenix-backend

          image: ahrenix/backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: ahrenix-config

            - secretRef:
                name: ahrenix-secret

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"

            limits:
              memory: "1Gi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 15
